#! /bin/bash
#
# v 0.4

#simple parsing, getopts to be done
if ( (expr "$1" : "^-" > /dev/null ) && (expr "$1" : ".*D.*" > /dev/null ) ); then 
  DEBUG=1;
  shift;
else
  DEBUG=0;
fi


echo -n $(date) $1

MAGECC_USER=$(cat $1 | grep "<username>" | sed 's/.*CDATA\[\(.*\)\]\].*/\1/')
MAGECC_DB=$(cat $1 | grep "<dbname>" | sed 's/.*CDATA\[\(.*\)\]\].*/\1/')
MAGECC_PW=$(cat $1 | grep "<password>" | sed 's/.*CDATA\[\(.*\)\]\].*/\1/')
MAGECC_HOST=$(cat $1 | grep "<host>" | sed 's/.*CDATA\[\(.*\)\]\].*/\1/')

if [[ "localhost" == $MAGECC_HOST ]]; then
  MAGECC_PROTO="";
else
  MAGECC_PROTO="--proto=tcp --port=4040";
fi

MAGECC_SQL_T='show tables;'

MAGECC_TABLE=$(mysql -B -u$MAGECC_USER -p$MAGECC_PW $MAGECC_PROTO -e "$MAGECC_SQL_T" $MAGECC_DB | grep core_cache_option)

# Password not shown
if (($DEBUG)); then echo; echo $MAGECC_USER $MAGECC_DB $MAGECC_HOST $MAGECC_PROTO $MAGECC_TABLE; fi

MAGECC_SQL_0='select * from '
MAGECC_SQL_0+="$MAGECC_TABLE;"


if (($DEBUG)); then mysql -N -u$MAGECC_USER -p$MAGECC_PW -e "$MAGECC_SQL_0" $MAGECC_PROTO $MAGECC_DB; fi


MAGECC_SQL_1="select count(code) from $MAGECC_TABLE where code!='0' and code!='1' and value='0';"
# mysql -B -u$MAGECC_USER -p$MAGECC_PW -e "$MAGECC_SQL_1" $MAGECC_PROTO $MAGECC_DB

MAGECC_RESULT1=$(mysql -B -N -u$MAGECC_USER -p$MAGECC_PW $MAGECC_PROTO -e "$MAGECC_SQL_1" $MAGECC_DB)

if (($MAGECC_RESULT1==0)); then
  echo " OK"; exit 0; 
else
  echo -n " " $MAGECC_RESULT1 "caches not active: "; 
  # further action!
  MAGECC_SQL_2="select code from $MAGECC_TABLE where code!='0' and code!='1' and value='0';";
  MAGECC_RESULT2=$(mysql -B -N -u$MAGECC_USER -p$MAGECC_PW $MAGECC_PROTO -e "$MAGECC_SQL_2" $MAGECC_DB);
  echo $MAGECC_RESULT2;
  #evaluation to integer
  #exit MAGECC_RESULT1
  exit 7;
fi
